[tool.poetry]
name = "lab5"
version = "0.1.0"
description = "Scraping dynamiczny"
authors = ["Natalia Grzybicka"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
selenium = "^4.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
